#pragma once

enum error_e {
    ERROR_STRING_OUT_OF_BOUND = 1,
    ERROR_UNDEFINED_ATTR_DOMAIN,
    ERROR_ATTR_DOMAIN_TYPE_MISMATCH,
    ERROR_VAR_MISSING,
    ERROR_LIST_TYPE_MISMATCH,
    ERROR_STRING_VAR_MISMATCH,
    ERROR_VALUE_TYPE_MISMATCH,
    ERROR_CANT_FIND_SUB,
};

